# ============================================================
# Feedback Control Micro-Drone
# dynamics.py — Rotational Dynamics, Version 0.1
#
# Purpose:
#   Convert the four motor thrusts into:
#       1. Roll torque
#       2. Pitch torque
#       3. Yaw torque
#
#   Then convert those torques into angular accelerations.
#
# This is our FIRST simplified dynamic model.
# ============================================================


# ------------------------------------------------------------
# 1. IMPORTS
# ------------------------------------------------------------

# "parameters" contains the physical properties of our drone:
# mass, wheelbase, inertia, maximum thrust, etc.
#
# We keep these in a separate file so that the physics equations
# don't contain random hard-coded numbers.
import param

# NumPy provides mathematical functions such as sqrt().
import numpy as np


# ------------------------------------------------------------
# 2. MOTOR GEOMETRY
# ------------------------------------------------------------

# Our quadrotor has a 135 mm motor-to-motor diagonal.
#
# We are using an X configuration, so the motors are positioned
# diagonally relative to the body x/y axes.
#
# The distance from the center of the drone to each motor is:
#
#       wheelbase / 2
#
# However, we need the x/y COMPONENT of that distance.
#
# Therefore:
#
#       motor_arm = wheelbase / (2 * sqrt(2))
#
# For our 135 mm wheelbase:
#
#       motor_arm ≈ 0.04773 m
#
# This is the moment arm used for roll and pitch torque.
motor_arm = param.wheelbase / (2 * np.sqrt(2))


# ------------------------------------------------------------
# 3. MOTOR THRUST → TORQUE
# ------------------------------------------------------------

def motor_torques(T1, T2, T3, T4):
    """
    Calculate the torque produced by the four motors.

    Parameters
    ----------
    T1, T2, T3, T4 : float
        Thrust produced by each motor in Newtons [N].

        Our motor arrangement is:

                    FRONT (+x)

              T1              T2
             CW              CCW

              T3              T4
             CCW              CW

                    REAR (-x)


        Coordinate convention:

            +x = forward
            +y = right
            +z = upward

    Returns
    -------
    tau_x : float
        Roll torque [N*m]

    tau_y : float
        Pitch torque [N*m]

    tau_z : float
        Yaw torque [N*m]
    """

    # --------------------------------------------------------
    # 3.1 Roll torque
    # --------------------------------------------------------

    # Roll is rotation around the x-axis.
    #
    # The right-side motors are T2 and T4.
    # The left-side motors are T1 and T3.
    #
    # If the right side produces more thrust than the left,
    # the drone experiences a roll torque.
    #
    # Torque = force × moment arm
    #
    # Therefore:
    #
    # tau_x = d[(T2 + T4) - (T1 + T3)]
    #
    # where d = motor_arm.
    tau_x = motor_arm * (
        (T2 + T4) - (T1 + T3)
    )


    # --------------------------------------------------------
    # 3.2 Pitch torque
    # --------------------------------------------------------

    # Pitch is rotation around the y-axis.
    #
    # The front motors are T1 and T2.
    # The rear motors are T3 and T4.
    #
    # More front thrust produces a pitch torque.
    #
    # Therefore:
    #
    # tau_y = d[(T1 + T2) - (T3 + T4)]
    tau_y = motor_arm * (
        (T1 + T2) - (T3 + T4)
    )


    # --------------------------------------------------------
    # 3.3 Yaw torque
    # --------------------------------------------------------

    # Yaw is rotation around the z-axis.
    #
    # Unlike roll and pitch, yaw torque does NOT primarily
    # come from the motors being displaced from the center.
    #
    # It comes from the reaction torque generated by the
    # spinning propellers.
    #
    # Our motor directions are:
    #
    #       T1 = CW
    #       T2 = CCW
    #       T3 = CCW
    #       T4 = CW
    #
    # Therefore:
    #
    #       CW thrust   -> one yaw direction
    #       CCW thrust  -> opposite yaw direction
    #
    # IMPORTANT:
    #
    # yaw_coefficient is currently a PLACEHOLDER.
    #
    # It is NOT measured data from our selected motor/propeller.
    # We will replace it later with a more physically defensible
    # motor/propeller model.
    yaw_coefficient = 0.02

    # CW motors are T1 and T4.
    # CCW motors are T2 and T3.
    #
    # An imbalance between these groups creates yaw torque.
    tau_z = yaw_coefficient * (
        (T1 + T4) - (T2 + T3)
    )


    # --------------------------------------------------------
    # 3.4 Return the three torques
    # --------------------------------------------------------

    # The function gives the caller all three rotational
    # torques at once.
    return tau_x, tau_y, tau_z


# ------------------------------------------------------------
# 4. TORQUE → ANGULAR ACCELERATION
# ------------------------------------------------------------

def angular_acceleration(tau_x, tau_y, tau_z):
    """
    Convert applied torque into angular acceleration.

    For our first simplified model we use:

        tau = I * alpha

    therefore:

        alpha = tau / I

    Parameters
    ----------
    tau_x : float
        Roll torque [N*m]

    tau_y : float
        Pitch torque [N*m]

    tau_z : float
        Yaw torque [N*m]

    Returns
    -------
    alpha_x : float
        Roll angular acceleration [rad/s^2]

    alpha_y : float
        Pitch angular acceleration [rad/s^2]

    alpha_z : float
        Yaw angular acceleration [rad/s^2]
    """

    # Roll angular acceleration.
    #
    # Ix is the drone's resistance to rotation around the
    # x-axis.
    alpha_x = tau_x / param.Ix

    # Pitch angular acceleration.
    #
    # Iy is the drone's resistance to rotation around the
    # y-axis.
    alpha_y = tau_y / param.Iy

    # Yaw angular acceleration.
    #
    # Iz is the drone's resistance to rotation around the
    # z-axis.
    alpha_z = tau_z / param.Iz

    return alpha_x, alpha_y, alpha_z


# ------------------------------------------------------------
# 5. SIMPLE TEST
# ------------------------------------------------------------

# This section only runs when we execute:
#
#       python dynamics.py
#
# It does NOT run when another file imports dynamics.py.
#
# That allows us to test this file independently.
if __name__ == "__main__":

    # --------------------------------------------------------
    # TEST 1 — Equal thrust
    # --------------------------------------------------------

    # Give every motor the same thrust.
    #
    # This represents a perfectly symmetric condition.
    #
    # If all four motors produce exactly the same thrust:
    #
    #   left  = right
    #   front = rear
    #   CW    = CCW
    #
    # Therefore we expect:
    #
    #   roll torque  = 0
    #   pitch torque = 0
    #   yaw torque   = 0
    T = param.max_thrust_per_motor

    tau_x, tau_y, tau_z = motor_torques(
        T, T, T, T
    )

    alpha_x, alpha_y, alpha_z = angular_acceleration(
        tau_x, tau_y, tau_z
    )

    print()
    print("TEST 1 — Equal thrust")
    print("----------------------")

    print(f"Motor thrust:          {T:.6f} N")

    print(f"Roll torque:           {tau_x:.6f} N*m")
    print(f"Pitch torque:          {tau_y:.6f} N*m")
    print(f"Yaw torque:            {tau_z:.6f} N*m")

    print(f"Roll acceleration:     {alpha_x:.6f} rad/s^2")
    print(f"Pitch acceleration:    {alpha_y:.6f} rad/s^2")
    print(f"Yaw acceleration:      {alpha_z:.6f} rad/s^2")


# ------------------------------------------------------------
# TEST 2 — Roll test
# ------------------------------------------------------------

# Start with 1 N of thrust from every motor.
#
# Then increase the RIGHT-side motors:
#
#       T2 and T4 = 1.2 N
#
# while the LEFT-side motors remain:
#
#       T1 and T3 = 1.0 N
#
# Because the right side has greater upward thrust,
# a roll torque should be produced.

T1 = 1.0
T2 = 1.2
T3 = 1.0
T4 = 1.2


# Convert motor thrusts into roll/pitch/yaw torque.
tau_x, tau_y, tau_z = motor_torques(
    T1, T2, T3, T4
)


# Convert torque into angular acceleration.
alpha_x, alpha_y, alpha_z = angular_acceleration(
    tau_x, tau_y, tau_z
)


print()
print("TEST 2 — Right-side thrust increase")
print("-----------------------------------")

print(f"T1: {T1:.2f} N")
print(f"T2: {T2:.2f} N")
print(f"T3: {T3:.2f} N")
print(f"T4: {T4:.2f} N")

print()

print(f"Roll torque:           {tau_x:.6f} N*m")
print(f"Pitch torque:          {tau_y:.6f} N*m")
print(f"Yaw torque:            {tau_z:.6f} N*m")

print()

print(f"Roll acceleration:     {alpha_x:.3f} rad/s^2")
print(f"Pitch acceleration:    {alpha_y:.3f} rad/s^2")
print(f"Yaw acceleration:      {alpha_z:.3f} rad/s^2")

# ============================================================
# END OF dynamics.py
# ============================================================